name: React app deployement

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: rishabhgupta/split-by@v1
        id: split
        with:
          string: ${{github.repository}}
          split-by: '/'

      - uses: actions/checkout@v2

      - name: Deploy react app to github pages
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
        env:
          PUBLIC_URL: /${{ steps.split.outputs._1 }}
